default:
    adapter: postgresql
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
development:
    adapter: postgresql
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
    database: db/development.sqlite3
test:
    adapter: postgresql
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
    database: db/test.sqlite3
production:
    adapter: postgresql
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
    database: db/production.sqlite3
